import Header from '../../components/Header';
import Footer from '../../components/Footer';

export default function TermsAndConditions() {
    return (
        <div className="min-h-screen flex flex-col relative bg-gradient-to-br from-blue-100 via-white to-purple-100">
            {/* Full-page shadow background */}
            <div className="fixed inset-0 z-0 flex items-center justify-center pointer-events-none">
                <div className="w-[90vw] h-[90vh] rounded-3xl shadow-2xl" style={{
                    boxShadow: '0 0 120px 40px rgba(80,110,255,0.18), 0 0 0 100vw rgba(255,255,255,0.7) inset',
                    background: 'transparent',
                }} />
            </div>
            <div className="relative z-10 flex flex-col min-h-screen">
                <Header />
                <main className="flex-1 flex justify-center items-center py-12 px-2 sm:px-4">
                    <div className="w-full max-w-4xl p-8 sm:p-12">
                        <h1 className="text-3xl sm:text-4xl font-extrabold text-center mb-2">Terms and Conditions</h1>
                        <h2 className="text-xl font-bold mb-1 text-center text-gray-800 drop-shadow">Terms of Service</h2>
                        <p className="text-sm text-gray-500 text-center mb-8">Effective Date: December 15, 2024</p>
                        <div className="prose prose-sm sm:prose-base max-w-none text-gray-800">
                            <h3 className="font-bold mb-4 mt-3">1. Introduction</h3>
                            <p>Welcome to storygen.co. These Terms of Service ("Terms") govern your access to and use of our website located at https://storygen.co ("Site") and the services we offer. By accessing or using our services, you agree to comply with these Terms. If you do not agree to any part of these Terms, you must not use our services.</p>
                            <h3 className="font-bold mb-2 mt-4">2. Definitions</h3>
                            <ul>
                                <li><b>User:</b> Any person accessing the Site and using the offered services.</li>
                                <li><b>Content:</b> Any information, text, images, videos, graphics, or other materials that the user creates, uploads, or shares via the Site.</li>
                                <li><b>Services:</b> All features and tools offered by storygen.co, including the creation, sharing, and management of AI-generated stories.</li>
                                <li><b>Client:</b> Any individual or legal entity using our services, whether for personal (B2C) or professional (B2B) purposes.</li>
                            </ul>
                            <h3 className="font-bold mb-2 mt-4">3. Description of Services</h3>
                            <ul>
                                <li>Creation of personalized stories generated by artificial intelligence.</li>
                                <li>Sharing and publishing created stories on various social platforms.</li>
                                <li>Interaction with a community of users through comments and feedback.</li>
                                <li>Access to exclusive content and advanced features based on subscription plans.</li>
                                <li>Dedicated customer support for B2B and B2C clients.</li>
                            </ul>
                            <p>We reserve the right to modify, suspend, or discontinue any or all of our services at any time without notice for maintenance, updates, or other reasons.</p>
                            <h3 className="font-bold mb-2 mt-4">4. User Accounts</h3>
                            <p>To access certain services, you must create a user account. You are responsible for maintaining the confidentiality of your login credentials and for all activities conducted under your account. You agree to notify storygen.co immediately of any unauthorized use of your account.</p>
                            <h3 className="font-bold mb-2 mt-4">5. User Obligations</h3>
                            <h4>5.1 Compliance with Laws</h4>
                            <ul>
                                <li>Use the services in compliance with applicable local, national, and international laws and regulations.</li>
                                <li>Not engage in fraudulent, illicit, or activities contrary to public order and good morals.</li>
                            </ul>
                            <h4>5.2 Respect for Third-Party Rights</h4>
                            <ul>
                                <li>Creating, uploading, publishing, or sharing any illegal, defamatory, abusive, threatening, harmful, obscene, pornographic, hate-inciting, or promoting violence or discrimination in any form.</li>
                                <li>Infringing on the intellectual property rights or image rights of third parties.</li>
                            </ul>
                            <h4>5.3 Security and Integrity of Services</h4>
                            <ul>
                                <li>Not attempt to gain unauthorized access to storygen.co's systems, databases, or services.</li>
                                <li>Not introduce malware (viruses, Trojan horses, etc.) or engage in any actions that could compromise the security, availability, or integrity of the services and other users.</li>
                            </ul>
                            <h4>5.4 Authenticity of Information</h4>
                            <p>You warrant that the information you provide during registration and use of the services is accurate, up-to-date, and complete.</p>
                            <h4>5.5 Age Restriction</h4>
                            <p>Access to and use of the services are strictly limited to individuals aged 18 or older. You certify that you have reached the minimum required age.</p>
                            <h3 className="font-bold mb-2 mt-4">6. Intellectual Property</h3>
                            <p>All content present on the Site, including but not limited to texts, graphics, logos, videos, and images, are the property of storygen.co or its partners and are protected by intellectual property laws. You are authorized to use this content solely for personal use of the services. Any commercial use requires prior written authorization from storygen.co.</p>
                            <h3 className="font-bold mb-2 mt-4">7. License of Use</h3>
                            <p>We grant you a limited, non-exclusive, and non-transferable license to use our services in accordance with these Terms. You may not reproduce, distribute, modify, or create derivative works based on our services without our written permission.</p>
                            <h3 className="font-bold mb-2 mt-4">8. User Generated Content</h3>
                            <p>You retain ownership of any content you create and share through our services. However, by using our services, you grant us a worldwide, non-exclusive, royalty-free license to use, reproduce, modify, and display such content as part of operating the Site and services.</p>
                            <h3 className="font-bold mb-2 mt-4">9. Data Protection and Privacy</h3>
                            <p>Your use of our services may require the provision of personal data. Please review our Privacy Policy to understand how we collect, use, and protect your personal information. We are committed to protecting your privacy and ensuring the security of your personal data. You have the right to access, rectify, and delete your personal information. To exercise these rights, please contact us.</p>
                            <h3 className="font-bold mb-2 mt-4">10. Use Restrictions</h3>
                            <ul>
                                <li>Attempt to bypass, disable, or otherwise interfere with the security features of our services.</li>
                                <li>Share, change, or disseminate copyrighted content without authorization.</li>
                                <li>Create or distribute pornographic, violent, hateful, or any other form of content prohibited by applicable laws.</li>
                                <li>Imitate others.</li>
                            </ul>
                            <h3 className="font-bold mb-2 mt-4">11. Minimum Age</h3>
                            <p>The use of storygen.co is reserved for individuals aged 18 or older. By creating an account or using our services, you declare and warrant that you are at least 18 years old.</p>
                            <h3 className="font-bold mb-2 mt-4">12. Right of Withdrawal</h3>
                            <p>Due to the integrative nature of the services provided and the costs associated with creating AI-generated content, storygen.co does not offer any right of withdrawal or refunds after the subscription or purchase of a service.</p>
                            <h3 className="font-bold mb-2 mt-4">13. Sales Conditions</h3>
                            <h4>13.1 Essential Features of the Services</h4>
                            <p>We provide a SaaS platform that allows users to create, customize, and publish AI-generated stories.</p>
                            <h4>13.2 Pricing</h4>
                            <p>Pricing and applicable taxes are clearly indicated on our Pricing page. Prices include all applicable taxes, detailed for every pay-as-you-go or specific service, which will be clearly communicated before billing.</p>
                            <h4>13.3 Payment Terms</h4>
                            <p>Payments are made exclusively through our secure payment service provider, Stripe. Subscriptions are offered in various plans, priced in US dollars (USD) on our site, and all payments are made monthly in this currency. Upon subscribing to a plan, it is automatically renewed each month on the anniversary date of the subscription. This information is clearly stated on the Stripe payment page. Users are responsible for managing their subscriptions, including tracking and cancellation if necessary. Some reminders may not be sent to notify users of an active subscription. No refunds will be issued in case of user oversight or failure to cancel.</p>
                            <p>Subscriptions are non-binding and can be canceled at any time directly from the platform; cancellation is immediate, and no billing will occur for the following cycle. Please retain the benefits of their subscription until the end of the current period.</p>
                            <p>Payments are securely processed via SSL protocol and Stripe's payment token management system, compliant with PCI-DSS standards. No banking data is stored on our servers. In the event of delayed or failed payment, storygen.co reserves the right to suspend or terminate your access to the services immediately, in accordance with the provisions outlined in our General Terms of Sale.</p>
                            <h4>13.4 Delivery of Execution Terms</h4>
                            <p>After purchasing a subscription, you will have immediate access to our services. Updates and improvements to the services are deployed regularly at no additional cost.</p>
                            <h4>13.5 Legal Warranties</h4>
                            <p>Our services benefit from the legal warranties of conformity and hidden defects as provided by Articles L217-4 and following of the French Consumer Code.</p>
                            <h4>13.6 After-Sales Service</h4>
                            <p>For any claims or assistance, please contact us with the contact form in the footer. Our support team is available Monday to Friday from 9 AM to 6 PM.</p>
                            <h4>13.7 Mediation</h4>
                            <p>In the event of a dispute, you have the option to resort free of charge to a consumer mediator whose contact details are available on our site.</p>
                            <h4>13.8 Company Contact Information</h4>
                            <p>storygen.co<br />Company Name: storygen.co<br />Registered Office Address: Corenc, 38700 France<br />SIRET Number: 84909323400016</p>
                            <h3 className="font-bold mb-2 mt-4">14. Warranty and Liability</h3>
                            <h4>14.1 Warranty of Conformity</h4>
                            <p>We guarantee that our services will conform to the description provided on our site at the time of purchase.</p>
                            <h4>14.2 Exclusion of Liability</h4>
                            <p>storygen.co shall in no event be liable for indirect, incidental, special, or punitive damages resulting from your use of the services, even if we have been advised of the possibility of such damages. This limitation applies even if storygen.co has been informed of the possibility of such damages.</p>
                            <h3 className="font-bold mb-2 mt-4">15. Limitation of Liability</h3>
                            <p>storygen.co shall not be liable for data loss, service interruptions, or other direct or indirect damages related to the use of our services, to the extent permitted by law.</p>
                            <h3 className="font-bold mb-2 mt-4">16. Indemnification</h3>
                            <p>You agree to indemnify and hold harmless storygen.co, its affiliates, officers, employees, and agents from any claims, damages, obligations, losses, liabilities, costs, or debts arising from your use of the services or your violation of the Terms.</p>
                            <h3 className="font-bold mb-2 mt-4">17. Applicable Law and Jurisdiction</h3>
                            <p>These Terms are governed by the laws of the French Republic. Any dispute arising from or related to these Terms will be subject to the exclusive jurisdiction of the courts located in Paris, France.</p>
                            <h3 className="font-bold mb-2 mt-4">18. Site Hosting</h3>
                            <p>The site storygen.co is hosted by Vercel Inc., a cloud platform for hosting websites and web services.</p>
                            <h3 className="font-bold mb-2 mt-4">19. General Provisions</h3>
                            <p>If any provision of these Terms is found to be invalid or unenforceable, the remaining provisions will remain in effect. Section titles are included for convenience and do not affect the interpretation of the Terms.</p>
                            <h3 className="font-bold mb-2 mt-4">20. Revision and Modification Clauses</h3>
                            <p>storygen.co reserves the right to unilaterally modify these Terms at any time. Changes will be published on this page and will take effect immediately. We commit to informing users of significant changes via our site or by email. Your continued use of the services after the publication of modifications constitutes your acceptance of the new Terms.</p>
                            <h3 className="font-bold mb-2 mt-4">21. Contact</h3>
                            <p>For any questions regarding these Terms, please contact us.</p>
                            <p className="text-center text-xs text-gray-400 mt-8">© 2025 @Byte All rights reserved.</p>
                            <div className="text-center mt-6">
                                <a href="/" className="text-blue-600 hover:underline">Return to Home</a>
                            </div>
                        </div>
                    </div>
                </main>
                <Footer />
            </div>
        </div>
    );
} 